openapi: 3.0.3
info:
  title: 'API Documentation - iCore - mini platforma blogowa'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://icore.test'
paths: []
tags: []
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
